// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: swipe_service.proto

package swipe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSwipesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwiperId      string                 `protobuf:"bytes,1,opt,name=swiper_id,json=swiperId,proto3" json:"swiper_id,omitempty"`
	TargetId      *string                `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3,oneof" json:"from,omitempty"`
	Till          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=till,proto3,oneof" json:"till,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwipesRequest) Reset() {
	*x = GetSwipesRequest{}
	mi := &file_swipe_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwipesRequest) ProtoMessage() {}

func (x *GetSwipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwipesRequest.ProtoReflect.Descriptor instead.
func (*GetSwipesRequest) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSwipesRequest) GetSwiperId() string {
	if x != nil {
		return x.SwiperId
	}
	return ""
}

func (x *GetSwipesRequest) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *GetSwipesRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetSwipesRequest) GetTill() *timestamppb.Timestamp {
	if x != nil {
		return x.Till
	}
	return nil
}

type GetSwipesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swipes        []*Swipe               `protobuf:"bytes,1,rep,name=swipes,proto3" json:"swipes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwipesResponse) Reset() {
	*x = GetSwipesResponse{}
	mi := &file_swipe_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwipesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwipesResponse) ProtoMessage() {}

func (x *GetSwipesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwipesResponse.ProtoReflect.Descriptor instead.
func (*GetSwipesResponse) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSwipesResponse) GetSwipes() []*Swipe {
	if x != nil {
		return x.Swipes
	}
	return nil
}

type Swipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwiperId      string                 `protobuf:"bytes,1,opt,name=swiper_id,json=swiperId,proto3" json:"swiper_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swipe) Reset() {
	*x = Swipe{}
	mi := &file_swipe_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swipe) ProtoMessage() {}

func (x *Swipe) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swipe.ProtoReflect.Descriptor instead.
func (*Swipe) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{2}
}

func (x *Swipe) GetSwiperId() string {
	if x != nil {
		return x.SwiperId
	}
	return ""
}

func (x *Swipe) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Swipe) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSwipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwiperId      string                 `protobuf:"bytes,1,opt,name=swiper_id,json=swiperId,proto3" json:"swiper_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSwipeRequest) Reset() {
	*x = CreateSwipeRequest{}
	mi := &file_swipe_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSwipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSwipeRequest) ProtoMessage() {}

func (x *CreateSwipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSwipeRequest.ProtoReflect.Descriptor instead.
func (*CreateSwipeRequest) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSwipeRequest) GetSwiperId() string {
	if x != nil {
		return x.SwiperId
	}
	return ""
}

func (x *CreateSwipeRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type CreateSwipeResonse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swipe         *Swipe                 `protobuf:"bytes,1,opt,name=swipe,proto3" json:"swipe,omitempty"`
	IsMatch       bool                   `protobuf:"varint,2,opt,name=is_match,json=isMatch,proto3" json:"is_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSwipeResonse) Reset() {
	*x = CreateSwipeResonse{}
	mi := &file_swipe_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSwipeResonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSwipeResonse) ProtoMessage() {}

func (x *CreateSwipeResonse) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSwipeResonse.ProtoReflect.Descriptor instead.
func (*CreateSwipeResonse) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSwipeResonse) GetSwipe() *Swipe {
	if x != nil {
		return x.Swipe
	}
	return nil
}

func (x *CreateSwipeResonse) GetIsMatch() bool {
	if x != nil {
		return x.IsMatch
	}
	return false
}

var File_swipe_service_proto protoreflect.FileDescriptor

const file_swipe_service_proto_rawDesc = "" +
	"\n" +
	"\x13swipe_service.proto\x12\rswipe_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\x10GetSwipesRequest\x12\x1b\n" +
	"\tswiper_id\x18\x01 \x01(\tR\bswiperId\x12 \n" +
	"\ttarget_id\x18\x02 \x01(\tH\x00R\btargetId\x88\x01\x01\x123\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x04from\x88\x01\x01\x123\n" +
	"\x04till\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x04till\x88\x01\x01B\f\n" +
	"\n" +
	"_target_idB\a\n" +
	"\x05_fromB\a\n" +
	"\x05_till\"A\n" +
	"\x11GetSwipesResponse\x12,\n" +
	"\x06swipes\x18\x01 \x03(\v2\x14.swipe_service.SwipeR\x06swipes\"|\n" +
	"\x05Swipe\x12\x1b\n" +
	"\tswiper_id\x18\x01 \x01(\tR\bswiperId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"N\n" +
	"\x12CreateSwipeRequest\x12\x1b\n" +
	"\tswiper_id\x18\x01 \x01(\tR\bswiperId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\"[\n" +
	"\x12CreateSwipeResonse\x12*\n" +
	"\x05swipe\x18\x01 \x01(\v2\x14.swipe_service.SwipeR\x05swipe\x12\x19\n" +
	"\bis_match\x18\x02 \x01(\bR\aisMatch2\xae\x01\n" +
	"\fSwipeService\x12N\n" +
	"\tGetSwipes\x12\x1f.swipe_service.GetSwipesRequest\x1a .swipe_service.GetSwipesResponse\x12N\n" +
	"\x06Create\x12!.swipe_service.CreateSwipeRequest\x1a!.swipe_service.CreateSwipeResonseB+Z)github.com/myselfBZ/uchrashuvda-isc/swipeb\x06proto3"

var (
	file_swipe_service_proto_rawDescOnce sync.Once
	file_swipe_service_proto_rawDescData []byte
)

func file_swipe_service_proto_rawDescGZIP() []byte {
	file_swipe_service_proto_rawDescOnce.Do(func() {
		file_swipe_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swipe_service_proto_rawDesc), len(file_swipe_service_proto_rawDesc)))
	})
	return file_swipe_service_proto_rawDescData
}

var file_swipe_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_swipe_service_proto_goTypes = []any{
	(*GetSwipesRequest)(nil),      // 0: swipe_service.GetSwipesRequest
	(*GetSwipesResponse)(nil),     // 1: swipe_service.GetSwipesResponse
	(*Swipe)(nil),                 // 2: swipe_service.Swipe
	(*CreateSwipeRequest)(nil),    // 3: swipe_service.CreateSwipeRequest
	(*CreateSwipeResonse)(nil),    // 4: swipe_service.CreateSwipeResonse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_swipe_service_proto_depIdxs = []int32{
	5, // 0: swipe_service.GetSwipesRequest.from:type_name -> google.protobuf.Timestamp
	5, // 1: swipe_service.GetSwipesRequest.till:type_name -> google.protobuf.Timestamp
	2, // 2: swipe_service.GetSwipesResponse.swipes:type_name -> swipe_service.Swipe
	5, // 3: swipe_service.Swipe.created_at:type_name -> google.protobuf.Timestamp
	2, // 4: swipe_service.CreateSwipeResonse.swipe:type_name -> swipe_service.Swipe
	0, // 5: swipe_service.SwipeService.GetSwipes:input_type -> swipe_service.GetSwipesRequest
	3, // 6: swipe_service.SwipeService.Create:input_type -> swipe_service.CreateSwipeRequest
	1, // 7: swipe_service.SwipeService.GetSwipes:output_type -> swipe_service.GetSwipesResponse
	4, // 8: swipe_service.SwipeService.Create:output_type -> swipe_service.CreateSwipeResonse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_swipe_service_proto_init() }
func file_swipe_service_proto_init() {
	if File_swipe_service_proto != nil {
		return
	}
	file_swipe_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swipe_service_proto_rawDesc), len(file_swipe_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swipe_service_proto_goTypes,
		DependencyIndexes: file_swipe_service_proto_depIdxs,
		MessageInfos:      file_swipe_service_proto_msgTypes,
	}.Build()
	File_swipe_service_proto = out.File
	file_swipe_service_proto_goTypes = nil
	file_swipe_service_proto_depIdxs = nil
}
