// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: swipe_service.proto

package swipe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwipeService_GetSwipes_FullMethodName = "/swipe_service.SwipeService/GetSwipes"
	SwipeService_Create_FullMethodName    = "/swipe_service.SwipeService/Create"
)

// SwipeServiceClient is the client API for SwipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwipeServiceClient interface {
	GetSwipes(ctx context.Context, in *GetSwipesRequest, opts ...grpc.CallOption) (*GetSwipesResponse, error)
	Create(ctx context.Context, in *CreateSwipeRequest, opts ...grpc.CallOption) (*CreateSwipeResonse, error)
}

type swipeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwipeServiceClient(cc grpc.ClientConnInterface) SwipeServiceClient {
	return &swipeServiceClient{cc}
}

func (c *swipeServiceClient) GetSwipes(ctx context.Context, in *GetSwipesRequest, opts ...grpc.CallOption) (*GetSwipesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwipesResponse)
	err := c.cc.Invoke(ctx, SwipeService_GetSwipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swipeServiceClient) Create(ctx context.Context, in *CreateSwipeRequest, opts ...grpc.CallOption) (*CreateSwipeResonse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSwipeResonse)
	err := c.cc.Invoke(ctx, SwipeService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwipeServiceServer is the server API for SwipeService service.
// All implementations must embed UnimplementedSwipeServiceServer
// for forward compatibility.
type SwipeServiceServer interface {
	GetSwipes(context.Context, *GetSwipesRequest) (*GetSwipesResponse, error)
	Create(context.Context, *CreateSwipeRequest) (*CreateSwipeResonse, error)
	mustEmbedUnimplementedSwipeServiceServer()
}

// UnimplementedSwipeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwipeServiceServer struct{}

func (UnimplementedSwipeServiceServer) GetSwipes(context.Context, *GetSwipesRequest) (*GetSwipesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwipes not implemented")
}
func (UnimplementedSwipeServiceServer) Create(context.Context, *CreateSwipeRequest) (*CreateSwipeResonse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSwipeServiceServer) mustEmbedUnimplementedSwipeServiceServer() {}
func (UnimplementedSwipeServiceServer) testEmbeddedByValue()                      {}

// UnsafeSwipeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwipeServiceServer will
// result in compilation errors.
type UnsafeSwipeServiceServer interface {
	mustEmbedUnimplementedSwipeServiceServer()
}

func RegisterSwipeServiceServer(s grpc.ServiceRegistrar, srv SwipeServiceServer) {
	// If the following call panics, it indicates UnimplementedSwipeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwipeService_ServiceDesc, srv)
}

func _SwipeService_GetSwipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwipeServiceServer).GetSwipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwipeService_GetSwipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwipeServiceServer).GetSwipes(ctx, req.(*GetSwipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwipeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSwipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwipeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwipeService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwipeServiceServer).Create(ctx, req.(*CreateSwipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwipeService_ServiceDesc is the grpc.ServiceDesc for SwipeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwipeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swipe_service.SwipeService",
	HandlerType: (*SwipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSwipes",
			Handler:    _SwipeService_GetSwipes_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SwipeService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swipe_service.proto",
}
